### ISSUE TITLE
Replace the current genome Collection_Date data with the well formatted date

### ISSUE THREAD

**Issue by chmao1** [PATRIC3/patric3_website#1019]
The Collection_Date is still using the old, uncleaned data. Please replace it with the cleaned data (in YYYY-MM-DD format). See the screenshot below.
<img width="1227" alt="screen shot 2016-10-10 at 3 18 33 pm" src="https://cloud.githubusercontent.com/assets/6361802/19248444/158da77c-8efe-11e6-8795-c2f8ac1ea8a5.png">

**Comment by dmachi** [comment]
Fixed and verified.

**Comment by chmao1** [comment]
Tested on beta. This is not yet fixed. Maulik, have you updated the solr?

![image](https://cloud.githubusercontent.com/assets/6361802/19449565/0c401ec2-9474-11e6-8f1b-ea4d498954a2.png)

**Comment by hyoo** [comment]
@maovt please verify that whether we reached the state or not. I couldn't remember out of my head.

**Comment by mshukla1** [comment]
We have a cleaner collection year field now, which is now displayed in tables instead of collection date. Collection date come in different formats depending on the data sources. We will treat it as unstructured string and not worry about making the format consistent.
