### ISSUE TITLE
bug in genome browser

### ISSUE THREAD

**Issue by jimdavis1** [PATRIC3/patric3_website#1095]
I was interested in  fig|1313.9910.peg.257, on the far right.  Note the pegs above it, 254,55 and 56.  If you click on them, they are all at least 900bases long, so something is wrong in the way they are being rendered.

Same is true of peg.239 and peg.240

![image](https://cloud.githubusercontent.com/assets/7661533/19401104/082724f4-921f-11e6-80e1-be60d639dc96.png)

![image](https://cloud.githubusercontent.com/assets/7661533/19401122/17fc8004-921f-11e6-9055-1e439dbaf513.png)

**Comment by aswarren** [comment]
This was due to lack of implemented stats function to determine when to turn off labels. This has been fixed.

**Comment by mshukla1** [comment]
@aswarren, has this been deployed? I am still seeing the same problem on alpha. The features close to the vertical grid lines seem to be truncated in display, specially when you zoom out to see ~50kb region. 

See the features in the screenshot below, on the right side, close to 37,500 line. 

https://www.alpha.patricbrc.org/view/Feature/PATRIC.1313.9910.1313.9910.con.0004.CDS.50079.51998.fwd#view_tab=genomeBrowser

<img width="920" alt="screen shot 2016-10-29 at 5 41 19 am" src="https://cloud.githubusercontent.com/assets/1236463/19828970/afc49ddc-9d9a-11e6-9356-7be33d39b4de.png">
