### ISSUE TITLE
Undefined features in Patric

### ISSUE THREAD

**Issue by Sveta-user** [PATRIC3/patric3_website#1659]
For some reason there are “undefined” pegs in Patric.  Where do these come from?   Furthermore,  they are listed at the top of Search results after any search  This is probably confusing for a user.
Could you fix these features?   If not, please do not allow these features to appear in  search results at least

<img width="545" alt="screen shot 2017-08-16 at 3 53 30 pm" src="https://user-images.githubusercontent.com/20665963/29384818-1c78049c-829b-11e7-8ae4-04667c7de70d.png">

**Comment by mshukla1** [comment]
when  addressing this, please check all other data types in the global search to make sure this doesn't happen elsewhere.

**Comment by chmao1** [comment]
Does this only happen for Specialty Genes?

**Comment by chmao1** [comment]
Instead of getting annotation source and type, I changed to fetch specialty gene property, source and evidence fields, which are more informative for specialty genes.

**Comment by chmao1** [comment]
Fixed and available on alpha.

**Comment by Sveta-user** [comment]
No, no, it is still not fixed on alpha!   Yes, the word "undefined" disappeared, but if you click on one of these Specialty genes returned - you get an empty page.  This is not good... Sorry to be so difficult

<img width="839" alt="screen shot 2017-08-22 at 4 17 23 pm" src="https://user-images.githubusercontent.com/20665963/29588085-ca5b3f20-8755-11e7-8b75-7d1eb47cfafa.png">

**Comment by chmao1** [comment]
Fixed the "undefined" issue. I'll create a new issue for the link problem.

**Comment by Sveta-user** [comment]
Got it, thank you!   
Shall I create a new issue for the mismatch between gene functions displayed on Search results page versus the actual gene functions displayed on the corresponding gene pages?  
What do you think?

**Comment by chmao1** [comment]
Yes, please. Thanks.

**Comment by hyoo** [comment]
![image](https://user-images.githubusercontent.com/1236467/29632832-d3a7454c-8809-11e7-853b-ecd33cb9aa55.png)

confirmed on production.
