### ISSUE TITLE
Feature Table: downloads from table toolbar not working

### ISSUE THREAD

**Issue by mshukla1** [PATRIC3/patric3_website#205]
...for both public and private genomes. 

-Maulik

**Comment by hyoo** [comment]
fixed and available on beta.

**Comment by mshukla1** [comment]
Harry, keeping it open because, I am still unable to get NA/AA sequences from table toolbar for PRIVATE GENOME.

**Comment by hyoo** [comment]
showing NA/AA sequences are fixed now.

**Comment by mshukla1** [comment]
able to get na/aa sequence from table toolbar now, even for private genomes.
