### ISSUE TITLE
Download from Search page-select features is not working

### ISSUE THREAD

**Issue by ARWattam** [PATRIC3/patric3_website#564]
I searched for Klebsiella and then clicked on the features, of which there was a multitude.  The table popped up, I clicked on the first 20, and tried to download.  It never did download and returned an error, a screenshot of which I provide below:
![screen shot 2015-12-10 at 11 08 30 am](https://cloud.githubusercontent.com/assets/11475316/11722502/a0a4f204-9f2e-11e5-9cf5-fc7e61c459d6.png)

**Comment by hyoo** [comment]
fixed and available on beta. BTW, download NEVER works with selection. I know it is confusing, but, this is how it is implemented consistently.

**Comment by ARWattam** [comment]
Can we fix that?  Does that mean that I would have to go and individually find the 20 features I wanted and download them separately?  Why do we have those little boxes in front of them, then?  Only to create a group?  Argh!!  So confusing to explain to people.

**Comment by mshukla1** [comment]
Harry, this is still not working on production. Has it been deployed?

**Comment by hyoo** [comment]
something went wrong. it is not working on beta as well. removed "fixed" label. will look and update soon.

**Comment by hyoo** [comment]
deployed in beta and double checked..
